/* contrib/sys_buffercache/sys_buffercache--1.0--1.1.sql */

-- complain if script is sourced in ksql, rather than via ALTER EXTENSION
\echo Use "ALTER EXTENSION SYS_BUFFERCACHE UPDATE TO '1.1'" to load this file. \quit

-- Upgrade view to 1.1. format
CREATE OR REPLACE VIEW SYS_BUFFERCACHE AS
	SELECT P.* FROM SYS_BUFFERCACHE_PAGES() AS P
	(BUFFERID INTEGER, RELFILENODE OID, RELTABLESPACE OID, RELDATABASE OID,
	 RELFORKNUMBER INT2, RELBLOCKNUMBER INT8, ISDIRTY BOOL, USAGECOUNT INT2,
	 PINNING_BACKENDS INT4);
